name: "CI With Flask Application"

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main # Workflow runs when changes are pushed to the 'main' branch

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build and Run Docker Container
        run: |
          # Stop and remove any existing container with the same name
          docker stop flask-app || true
          docker rm flask-app || true
          
          # Build and run the Docker container
          docker run -d --name flask-app -v ${{ github.workspace }}:/app -p 5000:5000 -w /app python:3.9-slim bash -c "pip install Flask==2.2.5 && python app.py"
          
          # Print out container logs for debugging
          docker logs flask-app
      - name: Removing The Container 
        run: |
           docker stop flask-app
           docker rm -f flask-app
