name: "CI With Flask Application"

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main # Workflow runs when changes are pushed to the 'main' branch

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Python Slim Docker image
        uses: docker://python:3.9-slim # Uses a minimal Python image

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install Flask==2.2.5

      - name: Restart PM2 process for Flask app
        run: |
          pm2 restart python-app || pm2 start app.py --name python-app # Start or restart the Flask app
