name: "CI With Flask Application"

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main # Workflow runs when changes are pushed to the 'main' branch

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python Slim Docker image
        run: |
          docker run -d --name flask-app -v ${{ github.workspace }}:/app -p 5000:5000 -w /app python:3.9-slim tail -f /dev/null # Run a minimal Python container in detached mode

      - name: Install Dependencies in Docker Container
        run: |
          docker exec flask-app python3 -m pip install --upgrade pip
          docker exec flask-app pip install Flask==2.2.5

      - name: Start Flask Application
        run: |
          docker exec flask-app python3 app.py # Start the Flask app

      - name: Install PM2
        run: |
          docker exec flask-app pip install pm2
          docker exec flask-app pm2 start app.py --interpreter python3 --name python-app # Start the Flask app with PM2

      - name: Check PM2 Status
        run: |
          docker exec flask-app pm2 list

      - name: Cleanup
        run: |
          docker stop flask-app
          docker rm flask-app
